apiVersion: v1
kind: Service
metadata:
  name: vmtest-app-service
spec:
  type: NodePort
  selector:
    app: vmtest-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      # 외부에서 접속할 포트 (예: http://192.168.63.98:30080)
      nodePort: 30080
